# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/107SO1CGNfC1l55ImbGDOSp_KRRVwGs3F
"""

#..................................Task no 1....................................


# Import required libraries
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Load Iris dataset
iris = sns.load_dataset("iris")

# Display dataset shape
print("Shape of Dataset:", iris.shape)

# Display column names
print("\nColumns:")
print(iris.columns)

# Display first 5 rows
print("\nFirst 5 Rows:")
print(iris.head())

# Dataset information
print("\nDataset Information:")
print(iris.info())

# Summary statistics
print("\nSummary Statistics:")
print(iris.describe())

# Scatter Plot
plt.figure(figsize=(8,5))
sns.scatterplot(data=iris,
                x='sepal_length',
                y='petal_length',
                hue='species')
plt.title("Sepal Length vs Petal Length")
plt.show()

# Histograms
iris.hist(figsize=(10,8))
plt.suptitle("Feature Distributions")
plt.show()

# Box Plots
plt.figure(figsize=(10,6))
sns.boxplot(data=iris)
plt.title("Box Plot for Outlier Detection")
plt.show()

from google.colab import files

uploaded = files.upload()

#........................task no 3...............................

# Import libraries
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import roc_curve, roc_auc_score

# Load dataset
df = pd.read_csv("heart.csv")

# Display first rows
print(df.head())

# Check missing values
print(df.isnull().sum())

# Simple EDA
sns.countplot(x='target', data=df)
plt.title("Heart Disease Distribution")
plt.show()

# Features and target
X = df.drop("target", axis=1)
y = df["target"]

# Split dataset
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)

# Create model
model = LogisticRegression(max_iter=1000)

# Train model
model.fit(X_train, y_train)

# Make predictions
y_pred = model.predict(X_test)

# Accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
print("\nConfusion Matrix:")
print(cm)

# ROC-AUC Score
roc_score = roc_auc_score(y_test, y_pred)
print("\nROC AUC Score:", roc_score)

# ROC Curve
fpr, tpr, threshold = roc_curve(y_test, y_pred)

plt.plot(fpr, tpr)
plt.plot([0,1],[0,1],'--')
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve")
plt.show()

# Feature Importance
importance = pd.DataFrame({
    "Feature": X.columns,
    "Importance": abs(model.coef_[0])
})

importance = importance.sort_values(
    by="Importance",
    ascending=False)

print("\nImportant Features:")
print(importance.head())

from google.colab import files

uploaded = files.upload()

#.........................task no6............................

# Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error

# Load dataset
df = pd.read_csv("Housing.csv")

# Display first 5 rows
print("First 5 Rows:")
print(df.head())

# Dataset information
print("\nDataset Info:")
print(df.info())

# Check missing values
print("\nMissing Values:")
print(df.isnull().sum())

# Convert categorical columns into numeric values
# This automatically converts yes/no and furnishing status

df = pd.get_dummies(df, drop_first=True)

# Features (input variables)
X = df.drop("price", axis=1)

# Target variable
y = df["price"]

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

# Create Linear Regression model
model = LinearRegression()

# Train model
model.fit(X_train, y_train)

# Predict house prices
y_pred = model.predict(X_test)

# Evaluate model

mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))

print("\nMean Absolute Error (MAE):", mae)
print("Root Mean Squared Error (RMSE):", rmse)

# Compare actual and predicted values

results = pd.DataFrame({
    "Actual Price": y_test,
    "Predicted Price": y_pred
})

print("\nSample Predictions:")
print(results.head(10))

# Plot Actual vs Predicted Prices

plt.figure(figsize=(8,6))

plt.scatter(y_test, y_pred)

plt.xlabel("Actual Prices")
plt.ylabel("Predicted Prices")
plt.title("Actual vs Predicted House Prices")

plt.show()